#!/bin/bash

# bak
# Creates a backup copy of your file/directory in the current directory
#
# Depends on: 
#   just bash


for arg in $@; do
    if [ ! -e "$arg" ]; then
        echo "[$0] $arg: File or directory not found."
    else
        cp -r "$arg" "${arg}.bak"
    fi
done

exit 0
