#!/bin/bash

# bak
# Creates a backup copy of your file/directory in the current directory

argv=("$@")

for arg in ${argv[@]}; do
    if [ ! -e "$arg" ]; then
        echo "[$0] $arg: File or directory not found."
    else
        cp -r "$arg" "${arg}.bak"
    fi
done

exit 0
