#!/bin/bash

# ctest
# Checks if the code compiles but gets rid of the binary
#
# Depends on: 
#   gcc

if ! command -v gcc &> /dev/null; then
    echo "[$0] gcc is not installed."
    exit
fi

tmp=$(/bin/mktemp)
trap 'rm -f $tmp' EXIT

/usr/bin/gcc "$1" -o "$tmp"
