#!/bin/bash

# docker-backup
#
# It says docker backup but it really just backs up
# my nextcloud data volume

nextcloud_data_directory="/var/lib/docker/volumes/nextcloud_nextcloud/_data/data"
if [ -d "$nextcloud_data_directory" ]; then
    if [ ! -d /mnt/backup/${nextcloud_data_directory} ]; then
            mkdir -p /mnt/backup/${nextcloud_data_directory}
    fi

    sudo rsync -avr ${nextcloud_data_directory}/* /mnt/backup/${nextcloud_data_directory} --progress $@
else
    echo "$nextcloud_data_directory not found"
fi
