#!/bin/bash

# frem
# Stands for "flush reminders"
# Serves a really specific purpose of just clearing my reminders file

reminders="$HOME/.reminders"

if [ -f "$reminders" ]; then
    echo "" > "$reminders"
    exit 0
else
    echo "[$0] File $reminders not found."
    exit 1
fi

exit 2
