#!/bin/bash

# hashdir
# Compiles the hashes of all files in a directory 
#
# Cuts out the file path before hashing a digest
#
# -c flag omits paths because it points to a temp file holding the hash values of all the files.

usage() {
    echo "hashdir"
    echo "Compiles the hashes of all files in a directory."
    echo ""
    echo "Usage:
    -h      Help
    -c      Compile hashes of all the files in the directory into one hash [default]
    -i      Keep individual hashes of each file"
}

# Default
individual_mode=true
while getopts "hci" flag; do 
    case $flag in
        h) 
            usage
            exit 1
            ;;
        c) 
            compile_mode=true
            individual_mode=false
            ;;
        i)
            individual_mode=true
            ;;
        \?)
            echo "Invalid option: $1" >&2
            usage
            exit 1
            ;;
    esac
    shift
done

argv=("$@")

for arg in "${argv[@]}"; do
    if [[ ! -d "$arg" ]]; then
        echo "[$0] Directory "$arg" not found" >&2
        exit 1
    fi
done


if [[ $compile_mode == true ]]; then
    for directory in "${argv[@]}"; do
        # Make temp file for piping hashes of multiple files
        temp=$(mktemp)
        trap 'rm -f "$temp"' EXIT

        # Hash files of the directory, cut paths, and stream to temp file
        find "$directory" -type f -exec sha256sum "{}" \+ | cut -d ' ' -f1 | sort > "$temp"
    done

    # Hashes all of the file hashes into one
    sha256sum "$temp" | cut -d ' ' -f1 >&1

    exit 0
fi


# Default
if [[ $individual_mode == true ]]; then
    for directory in "${argv[@]}"; do
        # Hash files of the directory and stream to stdout
        find "$directory" -type f -exec sha256sum "{}" \+ >&1
    done

    exit 0
fi

echo "[$0] Unknown error occured" >&2
exit 1
