#!/bin/bash

# hashdir
# Compiles the hashes of all files in a directory 

usage() {
    echo "hashdir"
    echo "Compiles the hashes of all files in a directory."
    echo ""
    echo "Usage:
    -h      Help
    -c      Compile hashes of all the files in the directory into one hash [default]
    -i      Keep individual hashes of each file"
}

# Default
individual_mode=true
while getopts "hci" flag; do 
    case $flag in
        h) 
            usage
            exit 1
            ;;
        c) 
            compile_mode=true
            individual_mode=false
            ;;
        i)
            individual_mode=true
            ;;
        \?)
            echo "Invalid option: $1" >&2
            usage
            exit 1
            ;;
    esac
    shift
done


directory="$1"
if [ ! -d "$directory" ]; then
	echo "[$0] Directory $directory not found"
	exit 1
fi

if [[ $compile_mode == true ]]; then
    # Make temp file for piping hashes of multiple files
    temp=$(/bin/mktemp)
    trap 'rm -f "$temp"' EXIT

    # Hash files of the directory and stream to temp file
    /bin/find "$directory" -type f -exec sha256sum {} + | /bin/sort > $temp

    # Hashes all of the file hashes into one
    /bin/sha256sum "$temp" > "$temp"

    # Cut the path of the hash because it points to the temp file
    echo "$(/bin/cut -d ' ' -f1 "$temp" )"

    exit 0
fi

# Default
if [[ $individual_mode == true ]]; then
    # Hash files of the directory and stream to stdout
    /bin/find "$directory" -type f -exec sha256sum {} +

    exit 0
fi

echo "[$0] Unknown error occured" >&2
exit 1
