#!/bin/bash

# hashcmp
# Checks if two or more hashes are the same
# Catches the first instance of a hash being different

RED="\e[1;31m"
GREEN="\e[1;32m"
NORMAL="\e[0m"

argc=$#
files=("$@")

# Error if two or less argcs
if (( argc < 2 )); then
    echo -e "${RED}[$0] ERROR: Argument count is less than 2.${NORMAL}"
    exit -1
fi


declare -a hashes
index=0
for file in "${files[@]}"; do
    # Check if files exist
    if [ ! -f "$file" ]; then
        echo "[$0] Cannot find file '$file'."
        exit -1
    fi

    # Sort $file
    sorted="$(mktemp)"
    echo "$(sort "$file")" > "$sorted"

    # Make a tempfile that stores the contents of $sorted after cutting paths of each hash
    sorted_hashes="$(mktemp)"

    # Cut paths of each hash
    while read line; do
        echo "$(echo "$line" | cut -d ' ' -f1)" >> $sorted_hashes
    done < "$sorted"

    # Append path to sorted cut file to the hashes array
    hashes[$index]="$sorted_hashes"
    index=$((index+1))
done

# Compare each hash file with the first one given
echo "Checking each file against file '${files[0]}'"...
failed=false
count=0
for (( i = 1; i < ${#hashes[@]}; i++ )); do
    if [[ ! -z "$(diff -q "${hashes[0]}" "${hashes[$i]}")" ]]; then
        echo -e "${RED}${files[$i]}: FAILED${NORMAL}"
        failed=true
        count=$((count+1))
    else echo -e "${GREEN}${files[$i]}: OK${NORMAL}"
    fi
done

echo ""
echo -e "[$0] result: $count file/s failed."
if [[ $failed == true ]]; then
    exit 1
else exit 0
fi

echo -e "${RED}Unknown error occured.${NORMAL}"
exit 1
