#!/bin/bash
## git@github.com/koeir/bashtools.git

# hashcmp
# Checks if two or more hashes are the same regardless of path
# Catches the first instance of a hash being different
#
# Depends on: 
#   just bash

RED="\e[1;31m"
GREEN="\e[1;32m"
NORMAL="\e[0m"
PN="$(basename $0)"

# flags
verbose=0

argc=$#
declare -a files

# Error if two or less argcs
if (( argc < 2 )); then
    echo -e "${PNERR} Argument count is less than 2."
    exit -1
fi

for arg in "$@"; do
    if [[ "${arg:0:1}" != "-" ]]; then
        files+=("$arg")
        continue
    fi

    for ((i=1; i<${#arg}; i++)); do
        case ${arg:i:1} in
            "v") verbose=1 ;;
            "n") 
                RED=""
                GREEN=""
                ;;
            *) 
                echo -e "${PNERR} ${letter}: Flag not found"
                exit
                ;;
        esac
    done
done

ERR="${RED}error:${NORMAL}"
PNERR="${PN}: ${ERR}"
FAILED="${RED}failed${NORMAL}"
OK="${GREEN}OK${NORMAL}"

unset letter flagNotFound


# An array containing filenames as keys and hashes as values
declare -a hashes
index=0
for file in "${files[@]}"; do
    
    # Check if files exist
    if [ ! -e "$file" ]; then
        echo -e "${PNERR} '$file': No such file or directory"
        exit -1
    fi

    if [ ! -f "$file" ]; then
        echo -e "${PNERR} '$file': Not a file"
        exit -1
    fi

    hashes[$index]="$(sort "$file" | cut -d ' ' -f1)"
    index=$((index+1))
done

# Compare each hash file with the first one given
ret=0
count=0
for (( i = 1; i < ${#hashes[@]}; i++ )); do

    if [[ "${hashes[0]}" != "${hashes[$i]}" ]]; then
        echo -e "${files[$i]}: $FAILED"
        ret=1
        count=$((count+1))
    else 
        echo -e "${files[$i]}: $OK"
    fi
done

if [ $verbose -eq 1 ]; then
    echo ""
    echo -e "${PN}: result: $count file/s failed."
fi

exit $ret
