#!/bin/bash

reminders_file="$HOME/.reminders"
PN="$(basename $0)"

_add() {
    if [ -z "$1" ]; then
        echo "$PN: $0: missing input"
        return 1
    fi

    echo "[ ] $1" >> $reminders_file 
}

_clear() {
    local tmpfile="$(mktemp)"
    echo "$PN: making copy to $tmpfile"

    if [ "$1" == "all" ]; then
        if [ ! -s "$reminders_file" ]; then
            cat "$reminders_file" > "$tmpfile"
        fi

        echo "$PN: clearing $reminders_file"
        echo -n "" > $reminders_file

        return 0
    fi

    local line="$1"

    sed -n "${line}p" "$reminders_file" | tee -a "$tmpfile"
    sed -i "${line}d" "$reminders_file"
    [ $? -ne 0 ] && return 1;
}

_uncomplete() { 
    if [[ "$1" == "all" ]]; then
        if [ $# -gt 2 ]; then
            echo "$PN: $0: too many arguments"
            return 1
        fi

        sed -i '1,$s/\[\*\]/[ ]/' "$reminders_file"
        if [ $? -ne 0 ]; then return $?; fi

        return 0
    fi

    local line="$1"

    sed -i "${line}s/\[\*\]/[ ]/" "$reminders_file"
    if [ $? -ne 0 ]; then return $?; fi

    sed -n "${line}p" "$reminders_file"
}

_complete() {
    if [ "$1" == "all" ]; then
        if [ $# -gt 2 ]; then
            echo "$PN: $0: too many arguments"
            return 1
        fi

        sed -i '1,$s/\[ \]/[*]/' "$reminders_file"
        if [ $? -ne 0 ]; then return $?; fi

        return 0
    fi

    local line="$1"

    sed -i "${line}s/\[ \]/[*]/" "$reminders_file"
    if [ $? -ne 0 ]; then return $?; fi

    sed -n "${line}p" "$reminders_file"
}

_ls() {
    local silent=false

    if [ "$1" == "silent" ]; then
        silent=true
    elif [[ "$1" =~ ^[0-9]* ]]; then
        line="$1"
    elif [[ ! -z "$1" ]]; then
        echo "$PN: $0: $1: unknown subcommand"
        return 1
    fi

    local list="$(cat $reminders_file)"

    if [ -z "$list" ]; then
        if ! $silent; then
            echo "$PN: you have no reminders"
        fi

        return 0
    fi

    if [ $? -ne 0 ]; then
        echo "$PN: $list"
        return 1
    fi

    if [ -n "$line" ]; then
        sed -n "${line}p" "$reminders_file"
        [ $? -ne 0 ] && return 1
        return 0
    fi

    echo "REMINDERS:"
    local count=1
    while IFS= read -r line; do
        echo "$count: $line"
        ((count++))
    done <<< "$list"
}

if [ ! -f "$reminders_file" ]; then
    if ! touch "$reminders_file"; then
        echo "$PN: error: $reminders_file: unable to create file"
        exit 1
    fi
fi

case $1 in
    "add")
        if [ $# -lt 2 ]; then
            echo "$PN: add: too few arguments"
            exit 1
        fi

        for msg in "${@:2}"; do
            _add "$msg"
        done

        _ls
        ;;
    "clear") 
        if [ -z "$2" ]; then 
            _clear "all"
            exit
        fi

        for arg in "${@:2}"; do
            _clear "$arg"
        done
        ;;
    "ls") 
       _ls "${@:2}"
        ;;
    "")
       _ls "silent"
        ;;
    "complete")
        if [ $# -lt 2 ]; then
            echo "$PN: complete: too few arguments"
            exit 1
        fi

        for task in "${@:2}"; do
            _complete "$task"
        done
        ;;
    "uncomplete")
        if [ $# -lt 2 ]; then
            echo "$PN: uncomplete: too few arguments"
            exit 1
        fi

        for task in "${@:2}"; do
            _uncomplete "$task"
        done
        ;;
    *)
        echo "$PN: error: $1: invalid subcommand"
        ;;
esac
