#!/bin/bash

reminders_file="$HOME/.reminders"
PN="$(basename $0)"
RED="\e[1;31m"
GREEN="\e[1;32m"
YELLOW="\e[1;33m"
NC="\e[0m"
ERROR="${RED}error${NC}"
WARNING="${YELLOW}warning${YELLOW}"

_add() {
    if [ -z "$1" ]; then
        echo -e "$PN: $ERROR: $0: missing input" >&2
        return 1
    fi

    echo "[ ] $1" >> "$reminders_file"
    return $?
}

_clear() {
    local tmpfile="$(mktemp)"
    echo "$PN: info: making copy to $tmpfile"

    if [ "$1" == "all" ]; then
        if [ -s "$reminders_file" ]; then
            cp "$reminders_file" "$tmpfile"
        fi

        echo "$PN: info: clearing $reminders_file"
        echo -n "" > $reminders_file

        return 0
    fi

    local line="$1"
    if [[ ! "$line" =~ ^[[:digit:]]*$ ]]; then
        echo -e "$PN: $ERROR: $0: must be a task number" >&2
        return 1
    fi

    sed -n "${line}p" "$reminders_file" | tee -a "$tmpfile"
    sed -i "${line}d" "$reminders_file"
    return $?
}

_uncomplete() {
    if [[ "$1" == "all" ]]; then
        if [ $# -gt 2 ]; then
            echo -e "$PN: $ERROR: $0: too many arguments" >&2
            return 1
        fi

        sed -i '1,$s/\[\*\]/[ ]/' "$reminders_file"
        return $?
    fi

    local line="$1"
    if [[ ! "$line" =~ ^[[:digit:]]*$ ]]; then
        echo -e "$PN: $ERROR: $0: must be a task number" >&2
        return 1
    fi

    sed -i "${line}s/\[\*\]/[ ]/" "$reminders_file"
    [ $? -eq 0 ] || return 1

    sed -n "${line}p" "$reminders_file"
    return $?
}

_complete() {
    if [ "$1" == "all" ]; then
        if [ $# -gt 2 ]; then
            echo -e "$PN: $ERROR: $0: too many arguments" >&2
            return 1
        fi

        sed -i '1,$s/\[ \]/[*]/' "$reminders_file"
        return $?
    fi

    local line="$1"
    if [[ ! "$line" =~ ^[[:digit:]]*$ ]]; then
        echo -e "$PN: $ERROR: $0: must be a task number" >&2
        return 1
    fi

    sed -i "${line}s/\[ \]/[*]/" "$reminders_file"
    [ $? -eq 0 ] || return 1

    sed -n "${line}p" "$reminders_file"
    return $?
}

_ls() {
    local silent=false
    local showUncompleted=false
    local showCompleted=false

    case "$1" in
        silent) silent=true ;;
        uncompleted) showUncompleted=true ;;
        completed) showCompleted=true ;;
        [[:digit:]]*) num="$1";;
        *)
            if [[ -n "$1" ]]; then
                echo -e "$PN: $ERROR: $0: $1: unknown subcommand" >&2
                return 1
            fi
            ;;
    esac

    local list="$(cat $reminders_file)"

    if [ -z "$list" ]; then
        if ! $silent; then
            echo "$PN: info: you have no reminders"
        fi

        return 0
    fi

    if [ $? -ne 0 ]; then
        echo "$PN: $list"
        return 1
    fi

    if [ -n "$num" ]; then
        if [[ ! "$num" =~ ^[[:digit:]]*$ ]]; then
            echo -e "$PN: $ERROR: $0: must be a task number" >&2
            return 1
        fi

        sed -n "${num}p" "$reminders_file"
        return $?
    fi

    echo "REMINDERS:"
    local count=0
    while IFS= read -r line; do
        count=$((++count))
        if $showCompleted; then
            grep "\[\*]" <<< "$line" &>/dev/null
            [ $? -eq 0 ] || continue
        elif $showUncompleted; then
            grep "\[ ]" <<< "$line" &>/dev/null
            [ $? -eq 0 ] || continue
        fi

        echo "$count: $line"
    done <<< "$list"
    return $?
}

if [ ! -f "$reminders_file" ]; then
    if ! touch "$reminders_file"; then
        echo -e "$PN: $ERROR: $reminders_file: unable to create file" >&2
        exit 1
    fi
fi

case $1 in
    "add")
        if [ $# -lt 2 ]; then
            echo -e "$PN: $ERROR: add: too few arguments" >&2
            exit 1
        fi

        for msg in "${@:2}"; do
            _add "$msg"
        done

        _ls
        ;;
    "clear")
        if [ -z "$2" ]; then
            _clear "all"
            exit
        fi

        for arg in "${@:2}"; do
            _clear "$arg"
        done
        ;;
    "ls")
       _ls "${@:2}"
        ;;
    "")
       _ls "silent"
        ;;
    "complete")
        if [ $# -lt 2 ]; then
            echo -e "$PN: $ERROR: complete: too few arguments" >&2
            exit 1
        fi

        for task in "${@:2}"; do
            _complete "$task"
        done
        ;;
    "uncomplete")
        if [ $# -lt 2 ]; then
            echo -e "$PN: $ERROR: uncomplete: too few arguments" >&2
            exit 1
        fi

        for task in "${@:2}"; do
            _uncomplete "$task"
        done
        ;;
    *)
        echo -e "$PN: $ERROR: $1: invalid subcommand" >&2
        exit 1
        ;;
esac
