#!/bin/bash

# rsync-full-backup
#
# Backs up the entire system into a directory, excluding temp/device/process stuff that is loaded on boot
#                                             (also excludes docker volumes)

set -e

usage() {
    echo "Usage: rsync-full-backup <backup-directory> [OPTIONAL: --rsync <rsync-flags>]"
}

if [[ $EUID != 0 ]]; then
    echo "[$0] Script must be ran as root."
    exit 1
fi

backupdir="$1"

if [[ -z "$backupdir" ]]; then
    echo "[$0] Missing argument: backup directory."
    usage
    exit 1
fi

if [[ ! -d "$backupdir" ]]; then
    echo "$backupdir: No such directory."
    usage
    exit 1
fi

# Shift until after --rsync flag
for arg in "$@"; do
    shift 1

    if [[ "$arg" == "--rsync" ]]; then break
    fi;
done

sudo rsync -aAXHv "/" "$backupdir" --progress \
    --numeric-ids \
    --log-file=/var/log/rsync-backup.log \
    --exclude=/dev/* \
    --exclude=/proc/* \
    --exclude=/sys/* \
    --exclude=/tmp/* \
    --exclude=/run/* \
    --exclude=/mnt/* \
    --exclude=/media/* \
    --exclude=/lost+found/ \
    --exclude=/var/run/* \
    --exclude=/var/lock/* \
    --exclude=/lib/modules/*/volatile/.mounted \
    --exclude=/var/cache/apt/archives/* \
    --exclude=/var/lib/docker/* \
    --exclude=/var/tmp/* \
    $@  # Include extra flags
