#!/bin/bash

# tmprm
## Compresses and moves file/dir to /tmp instead of outright rm'ing

doCompression=true
if [ ! -x "/usr/bin/gzip" ]; then
    echo "[$0] WARNING: /usr/bin/gzip not found. Will be unable to compress files."
    doCompression=false
fi

for item in $@; do
    if [ ! -e "$item" ]; then
        echo "[$0] WARNING: Unable to find \"$item\". Skipping..."
        continue
    fi

    if $doCompression; then
        gzip -1r "$item"
        if [ ! -d "$item" ]; then item="$item.gz"
        fi
    fi

    if ! mv "$item" /tmp; then
        echo "[$0] WARNING: Error while moving \"$item\"."
    fi
done
