#!/bin/bash

# tmprm
## Compresses and moves file/dir to /tmp instead of outright rm'ing
#
# Depends on:
#   gzip (optional)
#   tar (optional)

doCompression=true

if ! command -v gzip &> /dev/null; then
    echo "[$0] gzip is not installed. Will be unable to compress files."
    doCompression=false
fi

for item in $@; do
    # If compress file
    if [ -e "$item" ]; then
        if doCompression; then
            gzip -1r "$item"
        fi

        command mv "$item" "/tmp"
    else
        echo "[$0] gzip is not installed. Will be unable to compress files."
    fi
done
